version: '3.8'

services:
  ai-video-generator:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REPLICATE_API_KEY=${REPLICATE_API_KEY}
    volumes:
      - ./uploads:/app/uploads
      - ./.env:/app/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
