services:
  - type: web
    name: ai-video-generator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: REPLICATE_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true
